#! /usr/bin/env python

import math

# this is what candidates ussually start with
def reverseString1(src):
  l = list(src) # convert input string to list of character
  r = list()
  for i in range(len(src)): # navigate input characters and add them to front of result character list 
    r.insert(0, l[i])
  print(''.join(r)) # joins each character into the list with a blank seperator (result is a string, instead of a list of chars)

# this is what people like to see
def reverseString2(src):
  l = list(src)
  cnt = int(math.floor(len(l) / 2)) # iteration count ends up being half or half - 1 the total length
  for i in range(cnt):
    j = len(l) - 1 - i
    l[i], l[j] = l[j], l[i]
  print(''.join(l))

# this is what you should really do
def reverseString0(src):
  print(src[::-1])

if __name__ == "__main__":
  str = "!dekrow esrever"
  reverseString0(str)
  reverseString1(str)
  reverseString2(str)
