#! /usr/bin/env python3

import sys
import math
import random
from optparse import OptionParser

if __name__ == '__main__':
    parser = OptionParser("usage: %prog length count seed")

    opts,args = parser.parse_args()

    if len(args) != 3:
        parser.error("wrong number of arguments, execute with --help to see usage")

    length = int(args[0])
    count = int(args[1])
    seed = int(args[2])

    if (length <= 0 or count <= 0):
        parser.error("length and count must be greater than 0")

    random.seed(seed)

    maxWidth = round(math.ceil(math.sqrt(length)))
    graph = []
    for i in range(0, count):
        width = random.randrange(maxWidth)
        start = random.randrange(length - maxWidth)
        end = start + width
        score = (1 + random.randrange(1 + width))
        graph.append((start, end, score))

    for n in graph:
        print(n[0], n[1], n[2])
